<?php

namespace Database\Seeders;
use App\Models\Order;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Order::insert([
 [
                'user_id' => 1,
                'vendor_id' => 1,
                'rider_id' => 1,
                'address_id' => 1,
                'order_number' => 'ORD001',
                'subtotal' => 1000,
                'delivery_fee' => 100,
                'discount' => 50,
                'tax' => 30,
                'total' => 1080,
                'payment_status' => 'paid',
                'order_status' => 'delivered',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => now(),
            ],
            [
                'user_id' => 2,
                'vendor_id' => 2,
                'rider_id' => 2,
                'address_id' => 2,
                'order_number' => 'ORD002',
                'subtotal' => 2000,
                'delivery_fee' => 150,
                'discount' => 100,
                'tax' => 60,
                'total' => 2110,
                'payment_status' => 'pending',
                'order_status' => 'processing',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 1,
                'vendor_id' => 2,
                'rider_id' => null,
                'address_id' => 1,
                'order_number' => 'ORD003',
                'subtotal' => 1500,
                'delivery_fee' => 120,
                'discount' => 0,
                'tax' => 45,
                'total' => 1665,
                'payment_status' => 'paid',
                'order_status' => 'pending',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 2,
                'vendor_id' => 1,
                'rider_id' => 1,
                'address_id' => 2,
                'order_number' => 'ORD004',
                'subtotal' => 2500,
                'delivery_fee' => 200,
                'discount' => 150,
                'tax' => 75,
                'total' => 2625,
                'payment_status' => 'paid',
                'order_status' => 'shipped',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 1,
                'vendor_id' => 1,
                'rider_id' => 2,
                'address_id' => 1,
                'order_number' => 'ORD005',
                'subtotal' => 1800,
                'delivery_fee' => 100,
                'discount' => 50,
                'tax' => 54,
                'total' => 1904,
                'payment_status' => 'pending',
                'order_status' => 'processing',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 2,
                'vendor_id' => 2,
                'rider_id' => null,
                'address_id' => 2,
                'order_number' => 'ORD006',
                'subtotal' => 3000,
                'delivery_fee' => 250,
                'discount' => 200,
                'tax' => 90,
                'total' => 3140,
                'payment_status' => 'paid',
                'order_status' => 'delivered',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => now(),
            ],
            [
                'user_id' => 1,
                'vendor_id' => 2,
                'rider_id' => 1,
                'address_id' => 1,
                'order_number' => 'ORD007',
                'subtotal' => 2200,
                'delivery_fee' => 150,
                'discount' => 100,
                'tax' => 66,
                'total' => 2316,
                'payment_status' => 'pending',
                'order_status' => 'pending',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 2,
                'vendor_id' => 1,
                'rider_id' => 2,
                'address_id' => 2,
                'order_number' => 'ORD008',
                'subtotal' => 2700,
                'delivery_fee' => 180,
                'discount' => 120,
                'tax' => 81,
                'total' => 2841,
                'payment_status' => 'paid',
                'order_status' => 'shipped',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 1,
                'vendor_id' => 1,
                'rider_id' => null,
                'address_id' => 1,
                'order_number' => 'ORD009',
                'subtotal' => 1600,
                'delivery_fee' => 100,
                'discount' => 80,
                'tax' => 48,
                'total' => 1668,
                'payment_status' => 'pending',
                'order_status' => 'pending',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => null,
            ],
            [
                'user_id' => 2,
                'vendor_id' => 2,
                'rider_id' => 1,
                'address_id' => 2,
                'order_number' => 'ORD010',
                'subtotal' => 3500,
                'delivery_fee' => 300,
                'discount' => 250,
                'tax' => 105,
                'total' => 3655,
                'payment_status' => 'paid',
                'order_status' => 'delivered',
                'notes' => null,
                'placed_at' => now(),
                'delivered_at' => now(),
            ],

        ]);
    }
}
