<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
           [
    'vendor_id' => 1,
    'category_id' => 2, 

    'name' => 'iPhone 13',
    'slug' => 'iphone-13',
    'short_description' => 'Latest Apple iPhone',
    'description' => 'High performance smartphone',
    'sku' => 'SKU001',
    'price' => 150000,
    'sale_price' => 140000,
    'stock' => 10,
    'main_image' => null,
    'is_active' => 1,
    'is_featured' => 1,
],
                // [
                //     'vendor_id' => 2,
                //     // 'category_id' => 2,
                //     'name' => 'Samsung Galaxy S21',
                //     'slug' => 'samsung-galaxy-s21',
                // 'short_description' => 'Samsung flagship phone',
                // 'description' => 'Powerful Android device',
                // 'sku' => 'SKU002',
                // 'price' => 130000,
                // 'sale_price' => 120000,
                // 'stock' => 15,
                // 'main_image' => null,
                // 'is_active' => 1,
                // 'is_featured' => 0,
            // ],
            // [
            //     'vendor_id' => 3,
            //     // 'category_id' => 3,
            //     'name' => 'Dell Laptop',
            //     'slug' => 'dell-laptop',
            //     'short_description' => 'Business laptop',
            //     'description' => 'Reliable performance laptop',
            //     'sku' => 'SKU003',
            //     'price' => 120000,
            //     'sale_price' => 110000,
            //     'stock' => 8,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 1,
            // ],
            // [
            //     'vendor_id' => 2,
            //     'category_id' => 4,
            //     'name' => 'Men Shirt',
            //     'slug' => 'men-shirt',
            //     'short_description' => 'Cotton shirt',
            //     'description' => 'Comfortable wear',
            //     'sku' => 'SKU004',
            //     'price' => 2500,
            //     'sale_price' => 2000,
            //     'stock' => 50,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 0,
            // ],
            // [
            //     'vendor_id' => 1,
            //     'category_id' => 5,
            //     'name' => 'Women Dress',
            //     'slug' => 'women-dress',
            //     'short_description' => 'Stylish dress',
            //     'description' => 'Modern fashion wear',
            //     'sku' => 'SKU005',
            //     'price' => 5000,
            //     'sale_price' => 4500,
            //     'stock' => 30,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 1,
            // ],
            // [
            //     'vendor_id' => 2,
            //     'category_id' => 6,
            //     'name' => 'Sofa Set',
            //     'slug' => 'sofa-set',
            //     'short_description' => 'Luxury sofa',
            //     'description' => 'Comfortable seating',
            //     'sku' => 'SKU006',
            //     'price' => 80000,
            //     'sale_price' => 75000,
            //     'stock' => 5,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 0,
            // ],
            // [
            //     'vendor_id' => 3,
            //     'category_id' => 7,
            //     'name' => 'Kitchen Set',
            //     'slug' => 'kitchen-set',
            //     'short_description' => 'Complete kitchen tools',
            //     'description' => 'Useful kitchen items',
            //     'sku' => 'SKU007',
            //     'price' => 7000,
            //     'sale_price' => 6500,
            //     'stock' => 20,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 1,
            // ],
            // [
            //     'vendor_id' => 3,
            //     'category_id' => 8,
            //     'name' => 'Book Collection',
            //     'slug' => 'book-collection',
            //     'short_description' => 'Set of books',
            //     'description' => 'Educational books',
            //     'sku' => 'SKU008',
            //     'price' => 3000,
            //     'sale_price' => 2500,
            //     'stock' => 40,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 0,
            // ],
            // [
            //     'vendor_id' => 2,
            //     'category_id' => 9,
            //     'name' => 'Headphones',
            //     'slug' => 'headphones',
            //     'short_description' => 'Wireless headphones',
            //     'description' => 'Noise cancelling',
            //     'sku' => 'SKU009',
            //     'price' => 6000,
            //     'sale_price' => 5500,
            //     'stock' => 25,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 1,
            // ],
            // [
            //     'vendor_id' => 1,
            //     'category_id' => 10,
            //     'name' => 'Smart Watch',
            //     'slug' => 'smart-watch',
            //     'short_description' => 'Fitness tracker watch',
            //     'description' => 'Track your health',
            //     'sku' => 'SKU010',
            //     'price' => 10000,
            //     'sale_price' => 9000,
            //     'stock' => 18,
            //     'main_image' => null,
            //     'is_active' => 1,
            //     'is_featured' => 0,
            // ],
        ]);
    }
}
