<?php

namespace Database\Seeders;
use App\Models\UserProfile;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        UserProfile::insert([
             [
                'user_id' => 1,
                'label' => 'Home',
                'full_name' => 'Ali Khan',
                'phone' => '03001234567',
                'address_line_1' => 'Street 1',
                'address_line_2' => 'House 10',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'postal_code' => '54000',
                'country' => 'Pakistan',
                'latitude' => 31.5204,
                'longitude' => 74.3587,
                'is_default' => 1,
            ],
            [
                'user_id' => 2,
                'label' => 'Office',
                'full_name' => 'Ahmed Raza',
                'phone' => '03011234567',
                'address_line_1' => 'Street 2',
                'address_line_2' => 'Building A',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'postal_code' => '74000',
                'country' => 'Pakistan',
                'latitude' => 24.8607,
                'longitude' => 67.0011,
                'is_default' => 1,
            ],
            [
                'user_id' => 3,
                'label' => 'Home',
                'full_name' => 'Usman Tariq',
                'phone' => '03021234567',
                'address_line_1' => 'Street 3',
                'address_line_2' => 'Flat 5',
                'city' => 'Islamabad',
                'state' => 'ICT',
                'postal_code' => '44000',
                'country' => 'Pakistan',
                'latitude' => 33.6844,
                'longitude' => 73.0479,
                'is_default' => 1,
            ],
            [
                'user_id' => 2,
                'label' => 'Office',
                'full_name' => 'Bilal Ahmed',
                'phone' => '03031234567',
                'address_line_1' => 'Street 4',
                'address_line_2' => 'Office 12',
                'city' => 'Faisalabad',
                'state' => 'Punjab',
                'postal_code' => '38000',
                'country' => 'Pakistan',
                'latitude' => 31.4504,
                'longitude' => 73.1350,
                'is_default' => 1,
            ],
            [
                'user_id' => 1,
                'label' => 'Home',
                'full_name' => 'Hassan Ali',
                'phone' => '03041234567',
                'address_line_1' => 'Street 5',
                'address_line_2' => 'House 22',
                'city' => 'Multan',
                'state' => 'Punjab',
                'postal_code' => '60000',
                'country' => 'Pakistan',
                'latitude' => 30.1575,
                'longitude' => 71.5249,
                'is_default' => 1,
            ],
            [
                'user_id' => 2,
                'label' => 'Office',
                'full_name' => 'Zain Abbas',
                'phone' => '03051234567',
                'address_line_1' => 'Street 6',
                'address_line_2' => 'Block B',
                'city' => 'Peshawar',
                'state' => 'KPK',
                'postal_code' => '25000',
                'country' => 'Pakistan',
                'latitude' => 34.0151,
                'longitude' => 71.5249,
                'is_default' => 1,
            ],
            [
                'user_id' => 1,
                'label' => 'Home',
                'full_name' => 'Saad Khan',
                'phone' => '03061234567',
                'address_line_1' => 'Street 7',
                'address_line_2' => 'House 7',
                'city' => 'Quetta',
                'state' => 'Balochistan',
                'postal_code' => '87300',
                'country' => 'Pakistan',
                'latitude' => 30.1798,
                'longitude' => 66.9750,
                'is_default' => 1,
            ],
            [
                'user_id' => 2,
                'label' => 'Office',
                'full_name' => 'Umar Farooq',
                'phone' => '03071234567',
                'address_line_1' => 'Street 8',
                'address_line_2' => 'Suite 3',
                'city' => 'Sialkot',
                'state' => 'Punjab',
                'postal_code' => '51310',
                'country' => 'Pakistan',
                'latitude' => 32.4945,
                'longitude' => 74.5229,
                'is_default' => 1,
            ],
            [
                'user_id' => 2,
                'label' => 'Home',
                'full_name' => 'Farhan Ali',
                'phone' => '03081234567',
                'address_line_1' => 'Street 9',
                'address_line_2' => 'House 15',
                'city' => 'Hyderabad',
                'state' => 'Sindh',
                'postal_code' => '71000',
                'country' => 'Pakistan',
                'latitude' => 25.3960,
                'longitude' => 68.3578,
                'is_default' => 1,
            ],
            [
                'user_id' => 1,
                'label' => 'Office',
                'full_name' => 'Imran Khan',
                'phone' => '03091234567',
                'address_line_1' => 'Street 10',
                'address_line_2' => 'Building C',
                'city' => 'Rawalpindi',
                'state' => 'Punjab',
                'postal_code' => '46000',
                'country' => 'Pakistan',
                'latitude' => 33.5651,
                'longitude' => 73.0169,
                'is_default' => 1,
            ],
        ]);
    }
}
