<?php

namespace Database\Seeders;
use App\Models\Vendor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
// use Illuminate\Support\Str;
class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Vendor::insert([
             [
                'user_id' => 1,
                'store_name' => 'Tech World',
                'store_slug' => 'tech-world',
                'logo' => null,
                'description' => 'Electronics and gadgets store',
                'address' => 'Street 1',
                'city' => 'Lahore',
                'country' => 'Pakistan',
                'commission_rate' => 10.50,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 2,
                'store_name' => 'Fashion Hub',
                'store_slug' => 'fashion-hub',
                'logo' => null,
                'description' => 'Clothing and apparel',
                'address' => 'Street 2',
                'city' => 'Karachi',
                'country' => 'Pakistan',
                'commission_rate' => 12.00,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 3,
                'store_name' => 'Mobile Zone',
                'store_slug' => 'mobile-zone',
                'logo' => null,
                'description' => 'Mobile phones and accessories',
                'address' => 'Street 3',
                'city' => 'Islamabad',
                'country' => 'Pakistan',
                'commission_rate' => 8.75,
                'is_approved' => 0,
                'is_active' => 1,
            ],
            [
                'user_id' => 1,
                'store_name' => 'Home Decor',
                'store_slug' => 'home-decor',
                'logo' => null,
                'description' => 'Furniture and decoration items',
                'address' => 'Street 4',
                'city' => 'Faisalabad',
                'country' => 'Pakistan',
                'commission_rate' => 15.00,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 2,
                'store_name' => 'Book Store',
                'store_slug' => 'book-store',
                'logo' => null,
                'description' => 'Books and stationery',
                'address' => 'Street 5',
                'city' => 'Multan',
                'country' => 'Pakistan',
                'commission_rate' => 5.50,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 3,
                'store_name' => 'Sports Arena',
                'store_slug' => 'sports-arena',
                'logo' => null,
                'description' => 'Sports equipment',
                'address' => 'Street 6',
                'city' => 'Peshawar',
                'country' => 'Pakistan',
                'commission_rate' => 9.25,
                'is_approved' => 0,
                'is_active' => 1,
            ],
            [
                'user_id' => 1,
                'store_name' => 'Beauty Care',
                'store_slug' => 'beauty-care',
                'logo' => null,
                'description' => 'Cosmetics and skincare',
                'address' => 'Street 7',
                'city' => 'Quetta',
                'country' => 'Pakistan',
                'commission_rate' => 11.00,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 2,
                'store_name' => 'Auto Parts',
                'store_slug' => 'auto-parts',
                'logo' => null,
                'description' => 'Car accessories',
                'address' => 'Street 8',
                'city' => 'Sialkot',
                'country' => 'Pakistan',
                'commission_rate' => 7.75,
                'is_approved' => 1,
                'is_active' => 0,
            ],
            [
                'user_id' => 3,
                'store_name' => 'Grocery Mart',
                'store_slug' => 'grocery-mart',
                'logo' => null,
                'description' => 'Daily grocery items',
                'address' => 'Street 9',
                'city' => 'Hyderabad',
                'country' => 'Pakistan',
                'commission_rate' => 6.00,
                'is_approved' => 1,
                'is_active' => 1,
            ],
            [
                'user_id' => 1,
                'store_name' => 'Pet Store',
                'store_slug' => 'pet-store',
                'logo' => null,
                'description' => 'Pet food and accessories',
                'address' => 'Street 10',
                'city' => 'Rawalpindi',
                'country' => 'Pakistan',
                'commission_rate' => 13.50,
                'is_approved' => 0,
                'is_active' => 1,
            ],
        ]);
    }
}
